### ISSUE TITLE
Menu item backgrounds are transparent

### ISSUE THREAD

**Issue by roblevintennis** [AgnosticUI/agnosticui#146]
Menu CSS for `menu-item` background is transparent and that causes issues:

![image](https://user-images.githubusercontent.com/142403/161887708-1767bb6d-3172-47fa-b457-f6b432bf8841.png)

Switch to using:

```css
.menu-item {
  --menu-item-background-color: var(--agnostic-menu-item-background-color, white);
...
  background-color: var(--menu-item-background-color);
}
```
