### ISSUE TITLE
Refactor Positional CSS

### ISSUE THREAD

**Issue by roblevintennis** [AgnosticUI/agnosticui#149]
@e111077 brought up feasibility of refactoring some part of AgnosticUI to make it more amenable to Lit:
https://twitter.com/techytacos/status/1511903354762395649

Still trying to grok some of the implications, but this touches on some known hacks within AgnosticUI (button groups are one example) that started their lives using "positional CSS" dependent on html structure that resulted in some ugly hacks:

[button-group.css](https://github.com/AgnosticUI/agnosticui/blob/master/agnostic-css/src/components/button/button-group.css#L9) relies on positional. But this could be refactored to be:

`.btn-group {...}` would simply establish the inline flexbox and row as it already does

All positional CSS would be moved into [button.css](https://github.com/AgnosticUI/agnosticui/blob/master/agnostic-css/src/components/button/button.css) and we would apply classes to represent what is being done now:

So
```css
.btn-group > button {
  border-radius: var(--agnostic-btn-radius, var(--agnostic-radius, 0.25rem));
}

would become
.btn-grouped {
  border-radius: var(--agnostic-btn-radius, var(--agnostic-radius, 0.25rem));
}
```

And the other stanzas same:

```css

.btn-group > button:not(:last-child) {
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
  margin-inline-end: -1px;
}

.btn-group > button:not(:first-child) {
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;
}

would become

.btn-grouped-first {}
.btn-grouped-last {}
```

and the consumer that's projecting those buttons "into the group" would be responsible for applying said classes to the buttons.

It's verbose and what not but utilizes inversion of control and allows for more flexibility. It would also mean removal of hacks like [these](https://github.com/AgnosticUI/agnosticui/blob/master/agnostic-svelte/copystyles.cjs#L104):

```js
/*
Need to match all three of these:
.btn-group > button {...
.btn-group > button:not(:last-child) {...
.btn-group > button:not(:first-child) {...
*/
css = css.replace(/(.*btn-group > )(button.* )/, "$1:global($2) ");
css = css.replace(/(.*btn-group > )(button.* )/, "$1:global($2) ");
css = css.replace(/(.*btn-group > )(button.* )/, "$1:global($2) ");
```

This would probably be done for other similar cases like Tabs, Avatar Groups, etc. I don't believe there are too many maybe a half dozen or so? Benefits would be worthwhile.

Also, since AgnosticUI is "supposed to" be loosely using [SMACSS](http://smacss.com/book/applicability) it would remove a pretty knarly violation there 😋

**Comment by e111077** [comment]
small nit

> amenable to Lit

to

> amenable to shadow DOM

This would make it implementable in almost every shadow DOM / Web Components library out there not just Lit

**Comment by e111077** [comment]
Also alternatively, `.btn` can just expose

```css
border-radius: var(--_agnostic-btn-border-radius);
```

and then this transform can look like this:

```css
.btn-group > button {
  border-radius: var(--agnostic-btn-radius, var(--agnostic-radius, 0.25rem));
}

/* would become */
.btn-group {
  --_agnostic-btn-border-radius: var(--agnostic-btn-radius, var(--agnostic-radius, 0.25rem));
}
```

working example: [here](https://lit.dev/playground/#project=W3sibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8YWctYnV0dG9uLWdyb3VwPlxuICAgIDx0ZW1wbGF0ZSBzaGFkb3dyb290PVwib3BlblwiPlxuICAgICAgPHN0eWxlPlxuICAgICAgICBkaXYge1xuICAgICAgICAgIC0tX2Fnbm9zdGljLWJ0bi1ib3JkZXItcmFkaXVzOiB2YXIoLS1hZ25vc3RpYy1idG4tcmFkaXVzLCB2YXIoLS1hZ25vc3RpYy1yYWRpdXMsIDAuMjVyZW0pKTtcbiAgICAgICAgfVxuICAgICAgPC9zdHlsZT5cbiAgICAgIDxkaXYgcm9sZT1cImdyb3VwXCI-XG4gICAgICAgIDxzbG90Pjwvc2xvdD5cbiAgICAgIDwvZGl2PlxuICAgIDwvdGVtcGxhdGU-XG5cbiAgICA8YWctYnV0dG9uPlxuICAgICAgPHRlbXBsYXRlIHNoYWRvd3Jvb3Q9XCJvcGVuXCI-XG4gICAgICAgIDxzdHlsZT5cbiAgICAgICAgICBidXR0b24ge1xuICAgICAgICAgICAgYm9yZGVyLXJhZGl1czogdmFyKC0tX2Fnbm9zdGljLWJ0bi1ib3JkZXItcmFkaXVzLCAwcHgpO1xuICAgICAgICAgIH1cbiAgICAgICAgPC9zdHlsZT5cbiAgICAgICAgPGJ1dHRvbj5cbiAgICAgICAgICA8c2xvdD48L3Nsb3Q-XG4gICAgICAgIDwvYnV0dG9uPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIFxuICAgICAgQnV0dG9uIENvbnRlbnQhXG4gICAgPC9hZy1idXR0b24-XG4gIDwvYWctYnV0dG9uLWdyb3VwPlxuICBcbiAgPHN0eWxlPlxuICAgIDpyb290IHtcbiAgICAgIC0tYWdub3N0aWMtYnRuLXJhZGl1czogNTBweDtcbiAgICB9XG4gIDwvc3R5bGU-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d)
